### ISSUE TITLE
Unbound certificate choice

### ISSUE THREAD

**Issue by stompro** [stompro/pfsense-import-certificate#1]
Unbound supports DNS over TLS (DOT) for local clients.  The unbound config needs to know which certificate to use, much like the web interface does.  

The script should have a flag to set the unbound certificate to the newly uploaded certificate, and to restart unbound.

$config['unbound']['sslcertref'] = "";

**Comment by Sailing74** [comment]
Would be nice indeed!

**Comment by stompro** [comment]
I'm just going to have it update the unbound certificate reference if DOT is enabled for unbound without making it optional.

**Comment by stompro** [comment]
There is a nice set of functions for checking to see which services use a cert and to restart all those services.... but for some reason unbound isn't included currently.  Probably just an oversite.  But for now Unbound will need to be restarted with it's own check.

https://redmine.pfsense.org/issues/15062

**Comment by stompro** [comment]
Added support for Unbound cert update.
