### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by celevra** [stompro/pfsense-import-certificate#3]
Just wanted to leave a thank you, is there a way to spend you a beer?

**Comment by uncaught** [comment]
Yes, this helped me, too!

Couldn't get the Acme-Plugin to work due to my namecheap DNS api requiring a whitelisted IP, which my pfsense doesn't have.

**Comment by stompro** [comment]
Your both welcome... sorry haven't checked in here for a while.  Glad you found it useful.  I love beer, and it looks like you are from Germany, I love German beer, but the logistics just seem hard :-).
